# Generated by Django 3.2.4 on 2021-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.IntegerField(default=1),
        ),
    ]
